version: 0.3.{build}
skip_tags: true
configuration: Release
platform: Any CPU
clone_depth: 2
branches:
  only:
  - master
assembly_info:
  patch: true
  file: 'src\**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
  - choco install gitlink -y
  - choco install docfx -y
before_build:
  - nuget restore src
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
  - ps: Remove-Item src\packages\OpenCover* -include ("*.pdb", "*.sln", "*.csproj") -recurse
  - GitLink .\
after_test:
# This runs the tests with OpenCover and publishes the report to Coverall
  - ps: .\src\CreateCoverage.ps1 src
  - docfx
environment:
  COVERALLS_REPO_TOKEN:
    secure: hmXmadCb4cGSBxriCSnrIAtRJF5Jz42rEKKfzJR8HdvY/PFIFUhWZu1xSgN237Se
build:
  project: src\Dapplo.Addons.sln
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
- provider: GitHub
  release: Dapplo.Addons-v$(appveyor_build_version)
  auth_token:
    secure: eBQPtXg53XgcvdcVY3wQAw6kkwNh+QhcsTDwzyQLLh6IOPyiePEaEhJR0D2YBjAj
  draft: false
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
