//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Dapplo.Addons.Bootstrapper")]
[assembly: AssemblyDescription("Bootstrapper for addons, uses autofac")]
[assembly: AssemblyCompany("Dapplo")]
[assembly: AssemblyProduct("Dapplo.Addons.Bootstrapper")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0-beta")]
[assembly: AssemblyCopyright("Copyright © Dapplo 2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: InternalsVisibleTo("Dapplo.Addons.Tests")]
